name: TreasureHunt
version: '1.0.0'
main: com.treasurehunt.TreasureHuntPlugin
api-version: '1.21'
author: ignLuc4s
description: A plugin to manage custom treasure across the world

commands:
  treasure:
    description: Main command for TreasureHunt plugin
    usage: /treasure <create|delete|completed|list|gui>
    permission: treasurehunt.admin
    aliases: [th]

permissions:
  treasurehunt.admin:
    description: Allows access to all treasure commands
    default: op
  treasurehunt.use:
    description: Allows players to click treasures
    default: true
